### ISSUE TITLE
Log messages during normal run

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-opsgenie#18]
Hi,

During a normal Pulumi run there is always a log message coming from the opsgenie provider:

```
Previewing update (test):
     Type                 Name       Plan     Info
     pulumi:pulumi:Stack  test                1 message

Diagnostics:
  pulumi:pulumi:Stack (test):
    INFO[2021-07-13T16:52:34.811336306+01:00] Client is configured with ApiUrl: api.opsgenie.com, LogLevel: info, RetryMaxCount: 10
```

Is it possible to suppress this?

**Comment by lukehoban** [comment]
> Is it possible to suppress this?

It is not expected that this is being reported.  Will need to look into this to ensure this doesn't get surfaced by default.

**Comment by stack72** [comment]
Hi @Sodki 

Sorry for the long response on this one :/ So I had a look into this and this happens at neither Pulumi nor Terraform Provider SDK level - it's actuall happening in the opsgenie-go-sdk - https://github.com/opsgenie/opsgenie-go-sdk-v2/blob/d0825cdedb9b4b60159b8759c699c3e8c70186f9/client/client.go#L249

this is beyond our control as there is no configuration that we can pass to disable this behaviour

I am sorry about this - I can raise an issue on that SDK level but there's no guarantee they will implement the changes

Paul

**Comment by Sodki** [comment]
Thank you for looking into this @stack72, would you mind opening the ticket upstream and linking it here, for completeness sake? After that I think this ticket can be closed since there's nothing that can be done. If they decide to fix it it can always be reopened. Much appreciated.

**Comment by stack72** [comment]
Thanks @Sodki 

I have requested the logging to be disabled - https://github.com/opsgenie/opsgenie-go-sdk-v2/issues/86

Sorry I couldn't do more here :/

Paul
