### ISSUE TITLE
CI API key does not allow acces to some features

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-opsgenie#362]
### What happened?

The API key we use in CI does not give us access to some of the features, like global integrations.

### Example

.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
This is likely because we're using a free tier account.

If we need to graduate to a paid tier, then we should open an internal request.

**Comment by VenelinMartinov** [comment]
Yup, it is indeed because we are using a free acount. Opened the issue here to track us sourcing a non-free one since it blocks https://github.com/pulumi/pulumi-opsgenie/issues/286

**Comment by iwahbe** [comment]
@VenelinMartinov @guineveresaenger What is the desired resolution here?

**Comment by VenelinMartinov** [comment]
We need a non-free tier account so we can freely test the resources.

**Comment by VenelinMartinov** [comment]
We need the next level which is 23$ per user. I could not get that and believe @mjeffryes was discussing getting some partner deal.
