### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-opsgenie#99]
### What happened?

The main branch is failing CI, as noted in #team-provider-alerts

CC @jazzyfresh perhaps something with the last commit.

### Expected Behavior

NA

### Steps to reproduce

NA

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jazzyfresh** [comment]
A bit strange since checks passed on my branch and I branched off latest commit 🥲

**Comment by t0yv0** [comment]
Wunderbar!
